bloggingtimes/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home,new_all_blogs,PostDetailView,all_blogs,Postcreateview,AddPostView,addpostsave
app_name = 'blog'
urlpatterns = [
    path('',home.as_view(),name="home"),
    path('blogs',all_blogs.as_view(),name="all-blog"),
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
    #path('createblog/',Postcreateview.as_view(),name="create-blog"),
    path('createblog',Postcreateview,name="Postcreateview"),
    path('new_all_blogs',new_all_blogs,name="new_all_blogs"),
    path('newblog',AddPostView,name="create_new"),
    path('addpostsave',addpostsave,name="addpostsave")
]

bloggingtimes/bloggingtimes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('users/',include('users.urls', namespace='users')),
]
'''
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

bloggingtimes/users/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import registerRender
from .views import register
from .views import loginRender
from .views import loginAuthenticate 
from .views import userLogout
from .views import editProfile
from .views import profile
from .views import userProfileEdit
from .views import updateAddress
from .views import updateEmail
from .views import updatePhone
from .views import updateInfo
from .views import updateProfilePic

app_name = 'users'
urlpatterns = [
    path('register', register, name="register"),
    path('registerRender', registerRender, name="register"),
    path('login', loginRender, name = 'login'),
    path('logined', loginAuthenticate, name = 'loginAuthenticate'),
    path('userLogout', userLogout, name = 'logout'),
    path('profile', profile, name = 'profile'),
    path('editprofile', editProfile, name = 'editProfile'),
    path('userProfileEdit', userProfileEdit, name = 'userProfileEdit'),
    path('updateAddress', updateAddress, name = 'updateAddress'),
    path('updateEmail', updateEmail, name = 'updateEmail'),
    path('updatePhone', updatePhone, name = 'updatePhone'),
    path('updateInfo', updateInfo, name = 'updateInfo'),
    path('updateProfilePic', updateProfilePic, name = 'updateProfilePic')
]

bloggingtimes/templates/all-blogs-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container d-flex align-items-center">
      <h1 class="logo mr-auto"><a href="#">BloggingTimes</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Blog Feed</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Mentors</a></li>
          <li><a href="#">Recent Blogs</a></li>
          <li><a href="#">Contact</a></li>
          <li class="book-a-table text-center">
            <a href="#">Sign Up Here</a>
          </li>
        </ul>
      </nav>
      <!-- .nav-menu -->
    </div>
  </header>
  <!-- End Header -->

    <main id="main">
      <section class="breadcrumbs">
        <div class="container">
          <div class="d-flex justify-content-between align-items-center">
            <h2>Blogs Page</h2>
            <ol>
              <li><a href="#">Home</a></li>
              <li>Blogs Page</li>
            </ol>
          </div>
        </div>
      </section>

      <section class="inner-page" >
        <div class="container" >
          <div class="container-fluid">
                <div class="row" >
                    <div class="col-12">
                        <form method="GET" action="" class="form-inline">                
                            <input class="form-control" name="search" type="search" placeholder="Search..." aria-label="Search">
                            <button class="btn" type="submit" style="color: #cda45e;">
                              <i class="fa fa-search"></i>
                            </button>                                
                        </form>
                    </div>                
                </div>            
                <div class="row" >
                  {% for result in blogs %}
                  <article class="col-12 col-md-6" data-aos="zoom-in"
                    data-aos-delay="100">
                        <hr>
                        <a href="{% url 'blog:post-detail' result.id%}" class="effect-lily">
                            <div>
                                <img src="{{result.thumnail_image.url}}" alt="Image" class="img-fluid" style="width:500px;height:300px">                            
                            </div>
                            <h2>{{result.title}}</h2>
                        </a>                    
                        {% comment  %}
                        <p class="pt-3">
                            {{result.content|safe}}
                        </p>   
                        {% endcomment %}
                        
                        <div class="d-flex justify-content-between pt-4">
                            <span>Travel . Events</span>
                            <span>{{result.date_posted}}</span>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-between">
                            
                            <span>by {{result.author}}</span>
                        </div>
                    </article>
                    {% empty %}
                    add something to show no results
                {% endfor %}
               
              
          
          </div>
        </div>
        {% if is_paginated %}
        <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li> {% endif %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
          {% if page_obj.has_next %}<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li> {% endif %}
        </ul>
        {% endif %}
        </div>
        </section>
     
        <!-- ======= Footer ======= -->
    
{% endblock %}

bloggingtimes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />

    <title>BloggingTime</title>
    <meta content="" name="descriptison" />
    <meta content="" name="keywords" />

    <!-- Favicons -->
    <link href="{%static 'img/favicon.png' %}" rel="icon" />
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} "
      rel="stylesheet"
    />
    <link href="{% static 'vendor/icofont/icofont.min.css' %} " rel="stylesheet" />
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %} " rel="stylesheet" />
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %} " rel="stylesheet" />
    <link
      href="{% static 'vendor/owl.carousel/assets/owl.carousel.min.css' %} "
      rel="stylesheet"
    />
    <link href="{% static 'vendor/venobox/venobox.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet" />

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  </head>
{% block content%}
    {% endblock %}
    <footer id="footer">
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-6">
              <div class="footer-info">
                <h3>BloggingTimes</h3>
                <p>
                  Thapar University <br />
                  Patiala, India<br /><br />
                  <strong>Phone:</strong> +1 5589 55488 55<br />
                  <strong>Email:</strong> info@example.com<br />
                </p>
                <div class="social-links mt-3">
                  <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                  <a href="#" class="facebook"
                    ><i class="bx bxl-facebook"></i
                  ></a>
                  <a href="#" class="instagram"
                    ><i class="bx bxl-instagram"></i
                  ></a>
                  <a href="#" class="google-plus"
                    ><i class="bx bxl-skype"></i
                  ></a>
                  <a href="#" class="linkedin"
                    ><i class="bx bxl-linkedin"></i
                  ></a>
                </div>
              </div>
            </div>

            <div class="col-lg-2 col-md-6 footer-links">
              <h4>Useful Links</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="#">Home</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="#">About us</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="#">Blog Feed</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Terms of service</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Privacy policy</a>
                </li>
              </ul>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
              <h4>Our Services</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Web Development</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Content Writing</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Internships</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Mentorship</a>
                </li>
              </ul>
            </div>

            <div class="col-lg-4 col-md-6 footer-newsletter">
              <h4>Our Newsletter</h4>
              <p>
                Tamen quem nulla quae legam multos aute sint culpa legam noster
                magna
              </p>
              <form action="" method="post">
                <input type="email" name="email" /><input
                  type="submit"
                  value="Subscribe"
                />
              </form>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>BloggingTimes</span></strong
          >. All Rights Reserved
        </div>
        <div class="credits">Designed by <a href="#">BloggingTimes</a></div>
      </div>
    </footer>
    <!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>
<script
      src="//code.tidio.co/0lvxlhnuxefffebj15lxztg1vhuhlph4.js"
      async
    ></script>
    <!-- Vendor JS Files -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'vendor/aos/aos.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

bloggingtimes/templates/create-blog.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
  <body>
  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container d-flex align-items-center">
      <h1 class="logo mr-auto"><a href="#">BloggingTimes</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Blog Feed</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Mentors</a></li>
          <li><a href="#">Recent Blogs</a></li>
          <li><a href="#">Contact</a></li>
          <li class="book-a-table text-center">
            <a href="#">Sign Up Here</a>
          </li>
        </ul>
      </nav>
      <!-- .nav-menu -->
    </div>
  </header>
  <!-- End Header -->


  <main id="main">
    <section class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Write Your Blog Here</h2>
          <ol>
            <li><a href="#">Home</a></li>
            <li>New Post</li>
          </ol>
        </div>
      </div>
    </section>

      <section class="inner-page" >
      
          <section id="book-a-table" class="book-a-table">
            <div class="container" data-aos="fade-up">
              <div class="section-title">
                <h2>Blog</h2>
                <p>Post A Blog</p>
              </div>
    
    <form method="POST" action="addpostsave"  role="form"
                data-aos="fade-up"
                data-aos-delay="100" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Post</button>
    </form>
    </div>
          </section>
       
        </section>
    <script>window.CKEDITOR_BASEPATH = '/static_in_env/ckeditor/ckeditor/';</script>
{% endblock %}

bloggingtimes/templates/errorPage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 HTML Template by Colorlib</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Cabin:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/css/style.css' %}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h3>Oops! Page not found</h3>
				<h1><span>4</span><span>0</span><span>4</span></h1>
			</div>
			<h2>we are sorry, but the page you requested was not found. Plesae try again</h2>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

bloggingtimes/templates/login.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex">
      <div class="contact-info mr-auto">
        <i class="icofont-phone"></i> +1 5589 55488 55
        <span class="d-none d-lg-inline-block"><i class="icofont-clock-time icofont-rotate-180"></i> Mon-Sat: 11:00 AM - 23:00 PM</span>
      </div>
      <div class="languages">
        <ul>
          <li>En</li>
          <li><a href="#">De</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="index.html">Restaurantly</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'blog:home' %}">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#feed">Blog Feed</a></li>
          <li><a href="#profile">Profile</a></li>
          <li><a href="#mentors">Mentors</a></li>
          <li><a href="#recentblogs">Recent Blogs</a></li>
          <li><a href="#contact">Contact</a></li>
          <li class="book-a-table text-center">
            <a href="#book-a-table">Sign Up Here</a>
          </li>
          <li class="book-a-table text-center">
            <a href="{% url 'users:login' %}">Log In</a>
          </li>
        </ul>
      </nav>

    </div>
  </header><!-- End Header -->

  <main id="main">
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Inner Page</h2>
          <ol>
            <li><a href="index.html">Home</a></li>
            <li>Inner Page</li>
          </ol>
        </div>

      </div>
    </section>

    <section class="inner-page">
     
    <!-- Default form login -->
    <div class="container" style="margin-top:30px">
        
      <div class="row justify-content-md-center align-items-center" style="position: relative;">
          <div>
          <form method = 'post' action = 'logined' class="text-center border border-light p-5"  action="#!">
            {% csrf_token %}
              <p class="book-a-table text-center">Sign in</p>

              <!-- Email -->
              <input type="text" name = "username" id="defaultLoginFormEmail" class="form-control mb-4" placeholder="Username">

              <!-- Password -->
              <input type="password" name = "password" id="defaultLoginFormPassword" class="form-control mb-4" placeholder="Password">

              <div class="d-flex justify-content-around">
                  <div>
                      <!-- Remember me -->

                  </div>
                  <div>
                      <!-- Forgot password -->
                      <a href="">Forgot password?</a>
                  </div>
              </div>

              <!-- Sign in button -->
              <button class="book-a-table text-center" type="submit">Sign in</button>
            <ul class="nav-menu d-none d-lg-block"> 
              <p class="book-a-table text-center"><a href="#book-a-table">Sign In</a></p>
            </ul>
              <!-- Register -->
              <p>Not a member?
                  <a href='register'>Register</a>
              </p>

              <!-- Social login -->
              <p>or sign in with:</p>
              <p>    Icons missing </p>
              <a href="#" class="mx-2" role="button"><i class="fab fa-facebook-f light-blue-text"></i></a>
              <a href="#" class="mx-2" role="button"><i class="fab fa-twitter light-blue-text"></i></a>
              <a href="#" class="mx-2" role="button"><i class="fab fa-linkedin-in light-blue-text"></i></a>
              <a href="#" class="mx-2" role="button"><i class="fab fa-github light-blue-text"></i></a>

          </form>
          <!-- Default form login -->
          </div>
      </div>

  </div>



    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  



 {% endblock content%}

bloggingtimes/templates/new-blog-post.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
  <body>
  <!-- ======= Header ======= -->
  <header id="header">
    <div class="container d-flex align-items-center">
      <h1 class="logo mr-auto"><a href="#">BloggingTimes</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Blog Feed</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Mentors</a></li>
          <li><a href="#">Recent Blogs</a></li>
          <li><a href="#">Contact</a></li>
          <li class="book-a-table text-center">
            <a href="#">Sign Up Here</a>
          </li>
        </ul>
      </nav>
      <!-- .nav-menu -->
    </div>
  </header>
  <!-- End Header -->


  <main id="main">
    <section class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Write Your Blog Here</h2>
          <ol>
            <li><a href="#">Home</a></li>
            <li>New Post</li>
          </ol>
        </div>
      </div>
    </section>

      <section class="inner-page" >
      
          <section id="book-a-table" class="book-a-table">
            <div class="container" data-aos="fade-up">
              <div class="section-title">
                <h2>Blog</h2>
                <p>Post A Blog</p>
              </div>
              <form
                method="POST"
                action="new_all_blogs"
                role="form"
                data-aos="fade-up"
                data-aos-delay="100"
                enctype="multipart/form-data">
                {% csrf_token %}
               
              <div class="form-row">
                  <div class="col-lg-4 col-md-6 form-group">
                 <input
                      type="text"
                      name="title"
                      class="form-control"
                      id="title"
                      placeholder="Title"
                    />
                  
                  </div>
                  <div class="col-lg-4 col-md-6 form-group" style="bottom:24px;">
                    Select thumbnail image
                <input
                      type="file"
                      name="thumimages"
                      class="form-control"
                      id="images"
                      
                    />
                
                  </div>
                  <div class="col-lg-4 col-md-6 form-group" style="bottom:24px;">
                  Select cover image
                 <input
                      type="file"
                      name="coverimages"
                      class="form-control"
                      id="images"
                    />
                 
                  </div>
                </div>
                <em>Please provide a links inside anchor tag<em>
                <div class="form-group">
              <textarea
                    class="form-control"
                    name="content"
                    rows="10"
                    placeholder="Blog content"
                  ></textarea>
              
                </div> 
                <div class="text-center">
                  <button type="submit">Post</button>
                </div>
              </form>
            </div>
          </section>
       
        </section>
       
    {% endblock %}

bloggingtimes/templates/test.html
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        {% if user.is_authenticated %}
        Hello, {{user.username}}
        <form action = 'userLogout'>
            <button type = 'submit'>Logout</button>            
        </form>
        {% else %}
        {{userData}}
        {% endif %}        
    </body>
</html>